version: '2'

services:
  jekyll:
    build: ./
    container_name: jekyll-server
    command: jekyll serve --watch --force_polling --verbose
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll